# Starter pipeline
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    allowTelemetryCollection: false

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformCLI@0
  inputs:
    command: 'version'
    allowTelemetryCollection: true